require('node:fs').mkdirSync('artifacts', {recursive:true});
const assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 const context=await browser.newContext();
 let requests=0;
 await context.route('https://www.googletagmanager.com/**',route=>{requests++;return route.fulfill({contentType:'text/javascript',body:''});});
 const page=await context.newPage();
 const key='douaaGeneratorAnalyticsConsent';
 const goto=()=>page.goto('http://127.0.0.1:8000/');
 const choose=async name=>{await page.getByRole('button',{name,exact:true}).click();};
 await goto();assert.equal(requests,0);assert(await page.locator('#analyticsConsentBanner').isVisible());
 await choose('Refuser');await goto();assert.equal(requests,0);assert(!(await page.locator('#analyticsConsentBanner').isVisible()));
 await choose('Cookies');await choose('Accepter');await page.waitForTimeout(100);assert.equal(requests,1);
 assert.equal(await page.evaluate(()=>window['ga-disable-G-54ZYPQCDM3']),false);
 const data=await page.evaluate(()=>window.dataLayer.map(x=>Array.from(x)));
 assert.equal(data.find(x=>x[0]==='config')[2].send_page_view,false);
 assert.equal(data.find(x=>x[0]==='event')[2].page_location,'http://127.0.0.1:8000/');
 await page.evaluate(()=>{document.cookie='_ga=test; path=/';window.trackEvent('search',{search_term:'private'});});
 assert.equal(await page.evaluate(()=>JSON.stringify(window.dataLayer).includes('private')),false);
 await choose('Cookies');await choose('Refuser');
 assert.equal(await page.evaluate(()=>window['ga-disable-G-54ZYPQCDM3']),true);
 assert(!(await context.cookies()).some(c=>c.name==='_ga'));
 await choose('Cookies');await choose('Accepter');assert.equal(requests,1);
 assert.equal(await page.evaluate(()=>window['ga-disable-G-54ZYPQCDM3']),false);
 const other=await context.newPage();await other.goto('http://127.0.0.1:8000/cgu/');
 await choose('Cookies');await choose('Refuser');await other.waitForTimeout(100);
 assert.equal(await other.evaluate(()=>window['ga-disable-G-54ZYPQCDM3']),true);
 await page.evaluate(key=>localStorage.setItem(key,JSON.stringify({value:'granted',expires:1})),key);
 const before=requests;await goto();assert.equal(requests,before);assert(await page.locator('#analyticsConsentBanner').isVisible());
 await page.evaluate(key=>localStorage.setItem(key,'granted'),key);await goto();assert.equal(requests,before);assert(await page.locator('#analyticsConsentBanner').isVisible());
 await choose('Refuser');await page.goto('http://127.0.0.1:8000/recherche/');
 const input=page.locator('#globalSearchInput');await input.fill('  ');
 assert.equal(await input.evaluate(e=>e.checkValidity()),false);
 await input.fill('pardon');await page.locator('#globalSearchForm button').click();assert(await page.locator('#searchResults').innerText());
 await input.fill('<script>alert(1)</script>');assert.equal(await page.locator('#searchResults script').count(),0);
 await goto();await page.locator('#generateBtn').click();assert(await page.locator('#selectionError').isVisible());
 await page.locator('.category-option').first().click();await page.locator('#generateBtn').click();assert(await page.locator('#resultSection').isVisible());
 console.log('PASS: first visit, refusal, persisted refusal, acceptance, minimal payload, withdrawal, cookie deletion, renewed acceptance, cross-tab withdrawal, expired/legacy choice, search validation, escaped results, generation validation.');
 await browser.close();
})();
